services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports: 
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      spring.datasource.username: ${SPRING_DATASOURCE_USERNAME}
      spring.datasource.password: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./backend:/src
      - maven-repo:/root/.m2
    command: mvn spring-boot:run
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  app-network:
    driver: bridge

volumes:
  maven-repo: