version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  frontend:
    build: ./frontend
    ports: 
      - "5173:80"
    networks:
      - app-network
    volumes:
      - ./frontend:/src
    
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DATABASE_URL: example
    volumes:
      - ./backend:/src